import { BookOpen, Utensils, Plane, MessageCircle, Hash, Palette, Users, Heart, Home, Smile, Sparkles } from "lucide-react";

export const LANG_META = {
  es: { name: "Espanhol", flag: "🇪🇸", accent: "#E63329", bg: "#FFCFCC", textPrimary: "#1A0A09", textSecondary: "#7A3530", borderColor: "#F4A9A6" },
  it: { name: "Italiano", flag: "🇮🇹", accent: "#1A7A4A", bg: "#C2EDD4", textPrimary: "#071A0E", textSecondary: "#1E5233", borderColor: "#90CFA9" },
  ru: { name: "Russo",    flag: "🇷🇺", accent: "#1B4FD8", bg: "#C7D7FA", textPrimary: "#060D2A", textSecondary: "#1A3BA8", borderColor: "#93ACEE" },
  fr: { name: "Francês",  flag: "🇫🇷", accent: "#1251A3", bg: "#C8D9F5", textPrimary: "#050F24", textSecondary: "#1251A3", borderColor: "#93B4E8" },
  de: { name: "Alemão",   flag: "🇩🇪", accent: "#B45309", bg: "#FEF3C7", textPrimary: "#1C0F00", textSecondary: "#78350F", borderColor: "#FCD34D" },
  en: { name: "Inglês → Português", flag: "🇧🇷", accent: "#1A6B3C", bg: "#D4EDDA", textPrimary: "#0A2E1A", textSecondary: "#1A6B3C", borderColor: "#74C494" },
};

export const DECKS = {
  cumprimentos: { label: "Cumprimentos",       icon: MessageCircle },
  alimentos:    { label: "Alimentos",          icon: Utensils      },
  viagem:       { label: "Viagem",             icon: Plane         },
  verbos:       { label: "Verbos",             icon: BookOpen      },
  numeros:      { label: "Números",            icon: Hash          },
  cores:        { label: "Cores",              icon: Palette       },
  familia:      { label: "Família",            icon: Users         },
  corpo:        { label: "Corpo Humano",       icon: Heart         },
  casa:         { label: "Casa & Objetos",     icon: Home          },
  adjetivos:    { label: "Adjetivos",          icon: Smile         },
  frases:       { label: "Frases & Expressões",icon: Sparkles      },
};

export const DECK_KEYS = Object.keys(DECKS);

export const VOCAB = {
  es: {
    cumprimentos: [
      { pt: "Olá",               target: "Hola",          phonetic: null },
      { pt: "Bom dia",           target: "Buenos días",   phonetic: null },
      { pt: "Boa tarde",         target: "Buenas tardes", phonetic: null },
      { pt: "Boa noite",         target: "Buenas noches", phonetic: null },
      { pt: "Obrigado/Obrigada", target: "Gracias",       phonetic: null },
      { pt: "Por favor",         target: "Por favor",     phonetic: null },
      { pt: "De nada",           target: "De nada",       phonetic: null },
      { pt: "Com licença",       target: "Con permiso",   phonetic: null },
      { pt: "Desculpe",          target: "Lo siento",     phonetic: null },
      { pt: "Tchau",             target: "Adiós",         phonetic: null },
    ],
    alimentos: [
      { pt: "Pão",    target: "Pan",      phonetic: null },
      { pt: "Água",   target: "Agua",     phonetic: null },
      { pt: "Carne",  target: "Carne",    phonetic: null },
      { pt: "Fruta",  target: "Fruta",    phonetic: null },
      { pt: "Leite",  target: "Leche",    phonetic: null },
      { pt: "Ovo",    target: "Huevo",    phonetic: null },
      { pt: "Arroz",  target: "Arroz",    phonetic: null },
      { pt: "Feijão", target: "Frijoles", phonetic: null },
      { pt: "Queijo", target: "Queso",    phonetic: null },
      { pt: "Vinho",  target: "Vino",     phonetic: null },
    ],
    viagem: [
      { pt: "Aeroporto",  target: "Aeropuerto", phonetic: null },
      { pt: "Hotel",      target: "Hotel",      phonetic: null },
      { pt: "Bilhete",    target: "Boleto",     phonetic: null },
      { pt: "Passaporte", target: "Pasaporte",  phonetic: null },
      { pt: "Mala",       target: "Maleta",     phonetic: null },
      { pt: "Trem",       target: "Tren",       phonetic: null },
      { pt: "Ônibus",     target: "Autobús",    phonetic: null },
      { pt: "Táxi",       target: "Taxi",       phonetic: null },
      { pt: "Mapa",       target: "Mapa",       phonetic: null },
      { pt: "Praia",      target: "Playa",      phonetic: null },
    ],
    verbos: [
      { pt: "Ser/Estar", target: "Ser/Estar", phonetic: null },
      { pt: "Ter",       target: "Tener",     phonetic: null },
      { pt: "Ir",        target: "Ir",        phonetic: null },
      { pt: "Querer",    target: "Querer",    phonetic: null },
      { pt: "Poder",     target: "Poder",     phonetic: null },
      { pt: "Fazer",     target: "Hacer",     phonetic: null },
      { pt: "Falar",     target: "Hablar",    phonetic: null },
      { pt: "Comer",     target: "Comer",     phonetic: null },
      { pt: "Beber",     target: "Beber",     phonetic: null },
      { pt: "Dormir",    target: "Dormir",    phonetic: null },
    ],
    numeros: [
      { pt: "Um",     target: "Uno",    phonetic: null },
      { pt: "Dois",   target: "Dos",    phonetic: null },
      { pt: "Três",   target: "Tres",   phonetic: null },
      { pt: "Quatro", target: "Cuatro", phonetic: null },
      { pt: "Cinco",  target: "Cinco",  phonetic: null },
      { pt: "Seis",   target: "Seis",   phonetic: null },
      { pt: "Sete",   target: "Siete",  phonetic: null },
      { pt: "Oito",   target: "Ocho",   phonetic: null },
      { pt: "Nove",   target: "Nueve",  phonetic: null },
      { pt: "Dez",    target: "Diez",   phonetic: null },
    ],
    cores: [
      { pt: "Vermelho", target: "Rojo",     phonetic: null },
      { pt: "Azul",     target: "Azul",     phonetic: null },
      { pt: "Amarelo",  target: "Amarillo", phonetic: null },
      { pt: "Verde",    target: "Verde",    phonetic: null },
      { pt: "Branco",   target: "Blanco",   phonetic: null },
      { pt: "Preto",    target: "Negro",    phonetic: null },
      { pt: "Laranja",  target: "Naranja",  phonetic: null },
      { pt: "Rosa",     target: "Rosa",     phonetic: null },
      { pt: "Roxo",     target: "Morado",   phonetic: null },
      { pt: "Cinza",    target: "Gris",     phonetic: null },
    ],
    familia: [
      { pt: "Mãe",   target: "Madre",   phonetic: null },
      { pt: "Pai",   target: "Padre",   phonetic: null },
      { pt: "Filho", target: "Hijo",    phonetic: null },
      { pt: "Filha", target: "Hija",    phonetic: null },
      { pt: "Irmão", target: "Hermano", phonetic: null },
      { pt: "Irmã",  target: "Hermana", phonetic: null },
      { pt: "Avó",   target: "Abuela",  phonetic: null },
      { pt: "Avô",   target: "Abuelo",  phonetic: null },
      { pt: "Tio",   target: "Tío",     phonetic: null },
      { pt: "Tia",   target: "Tía",     phonetic: null },
    ],
    corpo: [
      { pt: "Cabeça",  target: "Cabeza",  phonetic: null },
      { pt: "Olho",    target: "Ojo",     phonetic: null },
      { pt: "Nariz",   target: "Nariz",   phonetic: null },
      { pt: "Boca",    target: "Boca",    phonetic: null },
      { pt: "Ouvido",  target: "Oído",    phonetic: null },
      { pt: "Mão",     target: "Mano",    phonetic: null },
      { pt: "Pé",      target: "Pie",     phonetic: null },
      { pt: "Coração", target: "Corazón", phonetic: null },
      { pt: "Costas",  target: "Espalda", phonetic: null },
      { pt: "Perna",   target: "Pierna",  phonetic: null },
    ],
    casa: [
      { pt: "Casa",     target: "Casa",     phonetic: null },
      { pt: "Porta",    target: "Puerta",   phonetic: null },
      { pt: "Janela",   target: "Ventana",  phonetic: null },
      { pt: "Mesa",     target: "Mesa",     phonetic: null },
      { pt: "Cadeira",  target: "Silla",    phonetic: null },
      { pt: "Cama",     target: "Cama",     phonetic: null },
      { pt: "Cozinha",  target: "Cocina",   phonetic: null },
      { pt: "Banheiro", target: "Baño",     phonetic: null },
      { pt: "Livro",    target: "Libro",    phonetic: null },
      { pt: "Telefone", target: "Teléfono", phonetic: null },
    ],
    adjetivos: [
      { pt: "Grande",  target: "Grande",   phonetic: null },
      { pt: "Pequeno", target: "Pequeño",  phonetic: null },
      { pt: "Bonito",  target: "Bonito",   phonetic: null },
      { pt: "Feio",    target: "Feo",      phonetic: null },
      { pt: "Rápido",  target: "Rápido",   phonetic: null },
      { pt: "Lento",   target: "Lento",    phonetic: null },
      { pt: "Quente",  target: "Caliente", phonetic: null },
      { pt: "Frio",    target: "Frío",     phonetic: null },
      { pt: "Feliz",   target: "Feliz",    phonetic: null },
      { pt: "Triste",  target: "Triste",   phonetic: null },
    ],
    frases: [
      { pt: "Quanto custa?",           target: "¿Cuánto cuesta?",           phonetic: null },
      { pt: "Não entendo",             target: "No entiendo",               phonetic: null },
      { pt: "Pode repetir?",           target: "¿Puede repetir?",           phonetic: null },
      { pt: "Onde fica o banheiro?",   target: "¿Dónde está el baño?",      phonetic: null },
      { pt: "Estou com fome",          target: "Tengo hambre",              phonetic: null },
      { pt: "Me chamo...",             target: "Me llamo...",               phonetic: null },
      { pt: "Fala português?",         target: "¿Habla portugués?",         phonetic: null },
      { pt: "Preciso de ajuda",        target: "Necesito ayuda",            phonetic: null },
      { pt: "Tudo bem?",               target: "¿Cómo estás?",              phonetic: null },
      { pt: "Com licença!",            target: "¡Con permiso!",             phonetic: null },
      { pt: "Onde fica o hotel?",      target: "¿Dónde está el hotel?",     phonetic: null },
      { pt: "Pode me ajudar?",         target: "¿Me puede ayudar?",         phonetic: null },
      { pt: "Não falo espanhol bem",   target: "No hablo bien español",     phonetic: null },
      { pt: "Qual é o seu nome?",      target: "¿Cómo se llama usted?",     phonetic: null },
      { pt: "Estou perdido(a)",        target: "Estoy perdido(a)",          phonetic: null },
      { pt: "Chame a polícia!",        target: "¡Llame a la policía!",      phonetic: null },
      { pt: "Que horas são?",          target: "¿Qué hora es?",             phonetic: null },
      { pt: "Tem Wi-Fi aqui?",         target: "¿Hay Wi-Fi aquí?",          phonetic: null },
      { pt: "A conta, por favor",      target: "La cuenta, por favor",      phonetic: null },
      { pt: "Posso pagar com cartão?", target: "¿Puedo pagar con tarjeta?", phonetic: null },
    ],
  },
  it: {
    cumprimentos: [
      { pt: "Olá",               target: "Ciao",            phonetic: null },
      { pt: "Bom dia",           target: "Buongiorno",      phonetic: null },
      { pt: "Boa tarde",         target: "Buon pomeriggio", phonetic: null },
      { pt: "Boa noite",         target: "Buonanotte",      phonetic: null },
      { pt: "Obrigado/Obrigada", target: "Grazie",          phonetic: null },
      { pt: "Por favor",         target: "Per favore",      phonetic: null },
      { pt: "De nada",           target: "Prego",           phonetic: null },
      { pt: "Com licença",       target: "Permesso",        phonetic: null },
      { pt: "Desculpe",          target: "Mi dispiace",     phonetic: null },
      { pt: "Tchau",             target: "Arrivederci",     phonetic: null },
    ],
    alimentos: [
      { pt: "Pão",    target: "Pane",      phonetic: null },
      { pt: "Água",   target: "Acqua",     phonetic: null },
      { pt: "Carne",  target: "Carne",     phonetic: null },
      { pt: "Fruta",  target: "Frutta",    phonetic: null },
      { pt: "Leite",  target: "Latte",     phonetic: null },
      { pt: "Ovo",    target: "Uovo",      phonetic: null },
      { pt: "Arroz",  target: "Riso",      phonetic: null },
      { pt: "Feijão", target: "Fagioli",   phonetic: null },
      { pt: "Queijo", target: "Formaggio", phonetic: null },
      { pt: "Vinho",  target: "Vino",      phonetic: null },
    ],
    viagem: [
      { pt: "Aeroporto",  target: "Aeroporto",  phonetic: null },
      { pt: "Hotel",      target: "Hotel",      phonetic: null },
      { pt: "Bilhete",    target: "Biglietto",  phonetic: null },
      { pt: "Passaporte", target: "Passaporto", phonetic: null },
      { pt: "Mala",       target: "Valigia",    phonetic: null },
      { pt: "Trem",       target: "Treno",      phonetic: null },
      { pt: "Ônibus",     target: "Autobus",    phonetic: null },
      { pt: "Táxi",       target: "Taxi",       phonetic: null },
      { pt: "Mapa",       target: "Mappa",      phonetic: null },
      { pt: "Praia",      target: "Spiaggia",   phonetic: null },
    ],
    verbos: [
      { pt: "Ser/Estar", target: "Essere/Stare", phonetic: null },
      { pt: "Ter",       target: "Avere",        phonetic: null },
      { pt: "Ir",        target: "Andare",       phonetic: null },
      { pt: "Querer",    target: "Volere",       phonetic: null },
      { pt: "Poder",     target: "Potere",       phonetic: null },
      { pt: "Fazer",     target: "Fare",         phonetic: null },
      { pt: "Falar",     target: "Parlare",      phonetic: null },
      { pt: "Comer",     target: "Mangiare",     phonetic: null },
      { pt: "Beber",     target: "Bere",         phonetic: null },
      { pt: "Dormir",    target: "Dormire",      phonetic: null },
    ],
    numeros: [
      { pt: "Um",     target: "Uno",     phonetic: null },
      { pt: "Dois",   target: "Due",     phonetic: null },
      { pt: "Três",   target: "Tre",     phonetic: null },
      { pt: "Quatro", target: "Quattro", phonetic: null },
      { pt: "Cinco",  target: "Cinque",  phonetic: null },
      { pt: "Seis",   target: "Sei",     phonetic: null },
      { pt: "Sete",   target: "Sette",   phonetic: null },
      { pt: "Oito",   target: "Otto",    phonetic: null },
      { pt: "Nove",   target: "Nove",    phonetic: null },
      { pt: "Dez",    target: "Dieci",   phonetic: null },
    ],
    cores: [
      { pt: "Vermelho", target: "Rosso",     phonetic: null },
      { pt: "Azul",     target: "Blu",       phonetic: null },
      { pt: "Amarelo",  target: "Giallo",    phonetic: null },
      { pt: "Verde",    target: "Verde",     phonetic: null },
      { pt: "Branco",   target: "Bianco",    phonetic: null },
      { pt: "Preto",    target: "Nero",      phonetic: null },
      { pt: "Laranja",  target: "Arancione", phonetic: null },
      { pt: "Rosa",     target: "Rosa",      phonetic: null },
      { pt: "Roxo",     target: "Viola",     phonetic: null },
      { pt: "Cinza",    target: "Grigio",    phonetic: null },
    ],
    familia: [
      { pt: "Mãe",   target: "Madre",    phonetic: null },
      { pt: "Pai",   target: "Padre",    phonetic: null },
      { pt: "Filho", target: "Figlio",   phonetic: null },
      { pt: "Filha", target: "Figlia",   phonetic: null },
      { pt: "Irmão", target: "Fratello", phonetic: null },
      { pt: "Irmã",  target: "Sorella",  phonetic: null },
      { pt: "Avó",   target: "Nonna",    phonetic: null },
      { pt: "Avô",   target: "Nonno",    phonetic: null },
      { pt: "Tio",   target: "Zio",      phonetic: null },
      { pt: "Tia",   target: "Zia",      phonetic: null },
    ],
    corpo: [
      { pt: "Cabeça",  target: "Testa",    phonetic: null },
      { pt: "Olho",    target: "Occhio",   phonetic: null },
      { pt: "Nariz",   target: "Naso",     phonetic: null },
      { pt: "Boca",    target: "Bocca",    phonetic: null },
      { pt: "Ouvido",  target: "Orecchio", phonetic: null },
      { pt: "Mão",     target: "Mano",     phonetic: null },
      { pt: "Pé",      target: "Piede",    phonetic: null },
      { pt: "Coração", target: "Cuore",    phonetic: null },
      { pt: "Costas",  target: "Schiena",  phonetic: null },
      { pt: "Perna",   target: "Gamba",    phonetic: null },
    ],
    casa: [
      { pt: "Casa",     target: "Casa",     phonetic: null },
      { pt: "Porta",    target: "Porta",    phonetic: null },
      { pt: "Janela",   target: "Finestra", phonetic: null },
      { pt: "Mesa",     target: "Tavolo",   phonetic: null },
      { pt: "Cadeira",  target: "Sedia",    phonetic: null },
      { pt: "Cama",     target: "Letto",    phonetic: null },
      { pt: "Cozinha",  target: "Cucina",   phonetic: null },
      { pt: "Banheiro", target: "Bagno",    phonetic: null },
      { pt: "Livro",    target: "Libro",    phonetic: null },
      { pt: "Telefone", target: "Telefono", phonetic: null },
    ],
    adjetivos: [
      { pt: "Grande",  target: "Grande",  phonetic: null },
      { pt: "Pequeno", target: "Piccolo", phonetic: null },
      { pt: "Bonito",  target: "Bello",   phonetic: null },
      { pt: "Feio",    target: "Brutto",  phonetic: null },
      { pt: "Rápido",  target: "Veloce",  phonetic: null },
      { pt: "Lento",   target: "Lento",   phonetic: null },
      { pt: "Quente",  target: "Caldo",   phonetic: null },
      { pt: "Frio",    target: "Freddo",  phonetic: null },
      { pt: "Feliz",   target: "Felice",  phonetic: null },
      { pt: "Triste",  target: "Triste",  phonetic: null },
    ],
    frases: [
      { pt: "Quanto custa?",           target: "Quanto costa?",              phonetic: null },
      { pt: "Não entendo",             target: "Non capisco",                phonetic: null },
      { pt: "Pode repetir?",           target: "Può ripetere?",              phonetic: null },
      { pt: "Onde fica o banheiro?",   target: "Dov'è il bagno?",            phonetic: null },
      { pt: "Estou com fome",          target: "Ho fame",                    phonetic: null },
      { pt: "Me chamo...",             target: "Mi chiamo...",               phonetic: null },
      { pt: "Fala português?",         target: "Parla portoghese?",          phonetic: null },
      { pt: "Preciso de ajuda",        target: "Ho bisogno di aiuto",        phonetic: null },
      { pt: "Tudo bem?",               target: "Come stai?",                 phonetic: null },
      { pt: "Com licença!",            target: "Permesso!",                  phonetic: null },
      { pt: "Onde fica o hotel?",      target: "Dov'è l'hotel?",             phonetic: null },
      { pt: "Pode me ajudar?",         target: "Può aiutarmi?",              phonetic: null },
      { pt: "Não falo italiano bem",   target: "Non parlo bene italiano",    phonetic: null },
      { pt: "Qual é o seu nome?",      target: "Come si chiama?",            phonetic: null },
      { pt: "Estou perdido(a)",        target: "Mi sono perso(a)",           phonetic: null },
      { pt: "Chame a polícia!",        target: "Chiami la polizia!",         phonetic: null },
      { pt: "Que horas são?",          target: "Che ore sono?",              phonetic: null },
      { pt: "Tem Wi-Fi aqui?",         target: "C'è il Wi-Fi qui?",          phonetic: null },
      { pt: "A conta, por favor",      target: "Il conto, per favore",       phonetic: null },
      { pt: "Posso pagar com cartão?", target: "Posso pagare con la carta?", phonetic: null },
    ],
  },
  ru: {
    cumprimentos: [
      { pt: "Olá",               target: "Привет",         phonetic: "[Privet]"          },
      { pt: "Bom dia",           target: "Доброе утро",    phonetic: "[Dobroye utro]"    },
      { pt: "Boa tarde",         target: "Добрый день",    phonetic: "[Dobry den']"      },
      { pt: "Boa noite",         target: "Спокойной ночи", phonetic: "[Spokóynoy nochi]" },
      { pt: "Obrigado/Obrigada", target: "Спасибо",        phonetic: "[Spasíbo]"         },
      { pt: "Por favor",         target: "Пожалуйста",     phonetic: "[Pojáluista]"      },
      { pt: "De nada",           target: "Не за что",      phonetic: "[Nye za chto]"     },
      { pt: "Com licença",       target: "Извините",       phonetic: "[Izvinyíte]"       },
      { pt: "Desculpe",          target: "Простите",       phonetic: "[Prostíte]"        },
      { pt: "Tchau",             target: "До свидания",    phonetic: "[Do svidánya]"     },
    ],
    alimentos: [
      { pt: "Pão",    target: "Хлеб",   phonetic: "[Khleb]"   },
      { pt: "Água",   target: "Вода",   phonetic: "[Vadá]"    },
      { pt: "Carne",  target: "Мясо",   phonetic: "[Myáso]"   },
      { pt: "Fruta",  target: "Фрукт",  phonetic: "[Frukt]"   },
      { pt: "Leite",  target: "Молоко", phonetic: "[Malakó]"  },
      { pt: "Ovo",    target: "Яйцо",   phonetic: "[Yaitsó]"  },
      { pt: "Arroz",  target: "Рис",    phonetic: "[Ris]"     },
      { pt: "Feijão", target: "Фасоль", phonetic: "[Fasol']"  },
      { pt: "Queijo", target: "Сыр",    phonetic: "[Sir]"     },
      { pt: "Vinho",  target: "Вино",   phonetic: "[Vinó]"    },
    ],
    viagem: [
      { pt: "Aeroporto",  target: "Аэропорт", phonetic: "[Aeropórt]" },
      { pt: "Hotel",      target: "Отель",    phonetic: "[Otel']"    },
      { pt: "Bilhete",    target: "Билет",    phonetic: "[Bilét]"    },
      { pt: "Passaporte", target: "Паспорт",  phonetic: "[Páspurt]"  },
      { pt: "Mala",       target: "Чемодан",  phonetic: "[Chemodán]" },
      { pt: "Trem",       target: "Поезд",    phonetic: "[Póyezd]"   },
      { pt: "Ônibus",     target: "Автобус",  phonetic: "[Avtóbus]"  },
      { pt: "Táxi",       target: "Такси",    phonetic: "[Taksí]"    },
      { pt: "Mapa",       target: "Карта",    phonetic: "[Kárta]"    },
      { pt: "Praia",      target: "Пляж",     phonetic: "[Plyaj]"    },
    ],
    verbos: [
      { pt: "Ser/Estar", target: "Быть",     phonetic: "[Bit']"     },
      { pt: "Ter",       target: "Иметь",    phonetic: "[Imét']"    },
      { pt: "Ir",        target: "Идти",     phonetic: "[Idtí]"     },
      { pt: "Querer",    target: "Хотеть",   phonetic: "[Khotét']"  },
      { pt: "Poder",     target: "Мочь",     phonetic: "[Moch']"    },
      { pt: "Fazer",     target: "Делать",   phonetic: "[Délat']"   },
      { pt: "Falar",     target: "Говорить", phonetic: "[Gavarít']" },
      { pt: "Comer",     target: "Есть",     phonetic: "[Yest']"    },
      { pt: "Beber",     target: "Пить",     phonetic: "[Pit']"     },
      { pt: "Dormir",    target: "Спать",    phonetic: "[Spat']"    },
    ],
    numeros: [
      { pt: "Um",     target: "Один",   phonetic: "[Adín]"     },
      { pt: "Dois",   target: "Два",    phonetic: "[Dva]"      },
      { pt: "Três",   target: "Три",    phonetic: "[Tri]"      },
      { pt: "Quatro", target: "Четыре", phonetic: "[Chetíre]"  },
      { pt: "Cinco",  target: "Пять",   phonetic: "[Pyat']"    },
      { pt: "Seis",   target: "Шесть",  phonetic: "[Shest']"   },
      { pt: "Sete",   target: "Семь",   phonetic: "[Sem']"     },
      { pt: "Oito",   target: "Восемь", phonetic: "[Vósem']"   },
      { pt: "Nove",   target: "Девять", phonetic: "[Dyévyat']" },
      { pt: "Dez",    target: "Десять", phonetic: "[Dyésat']"  },
    ],
    cores: [
      { pt: "Vermelho", target: "Красный",    phonetic: "[Krásniy]"     },
      { pt: "Azul",     target: "Синий",      phonetic: "[Síniy]"       },
      { pt: "Amarelo",  target: "Жёлтый",     phonetic: "[Jóltiy]"      },
      { pt: "Verde",    target: "Зелёный",    phonetic: "[Zelóniy]"     },
      { pt: "Branco",   target: "Белый",      phonetic: "[Béliy]"       },
      { pt: "Preto",    target: "Чёрный",     phonetic: "[Chórniy]"     },
      { pt: "Laranja",  target: "Оранжевый",  phonetic: "[Aránjiviy]"   },
      { pt: "Rosa",     target: "Розовый",    phonetic: "[Rózoviy]"     },
      { pt: "Roxo",     target: "Фиолетовый", phonetic: "[Fialyétoviy]" },
      { pt: "Cinza",    target: "Серый",      phonetic: "[Sériy]"       },
    ],
    familia: [
      { pt: "Mãe",   target: "Мама",    phonetic: "[Máma]"      },
      { pt: "Pai",   target: "Папа",    phonetic: "[Pápa]"      },
      { pt: "Filho", target: "Сын",     phonetic: "[Sin]"       },
      { pt: "Filha", target: "Дочь",    phonetic: "[Doch']"     },
      { pt: "Irmão", target: "Брат",    phonetic: "[Brat]"      },
      { pt: "Irmã",  target: "Сестра",  phonetic: "[Sistrá]"    },
      { pt: "Avó",   target: "Бабушка", phonetic: "[Bábushka]"  },
      { pt: "Avô",   target: "Дедушка", phonetic: "[Dyédushka]" },
      { pt: "Tio",   target: "Дядя",    phonetic: "[Dyádya]"    },
      { pt: "Tia",   target: "Тётя",    phonetic: "[Tyótya]"    },
    ],
    corpo: [
      { pt: "Cabeça",  target: "Голова", phonetic: "[Galavá]"  },
      { pt: "Olho",    target: "Глаз",   phonetic: "[Glas]"    },
      { pt: "Nariz",   target: "Нос",    phonetic: "[Nos]"     },
      { pt: "Boca",    target: "Рот",    phonetic: "[Rot]"     },
      { pt: "Ouvido",  target: "Ухо",    phonetic: "[Úkho]"    },
      { pt: "Mão",     target: "Рука",   phonetic: "[Ruká]"    },
      { pt: "Pé",      target: "Ступня", phonetic: "[Stupnyá]" },
      { pt: "Coração", target: "Сердце", phonetic: "[Syértse]" },
      { pt: "Costas",  target: "Спина",  phonetic: "[Spiná]"   },
      { pt: "Perna",   target: "Нога",   phonetic: "[Nagá]"    },
    ],
    casa: [
      { pt: "Casa",     target: "Дом",     phonetic: "[Dom]"     },
      { pt: "Porta",    target: "Дверь",   phonetic: "[Dver']"   },
      { pt: "Janela",   target: "Окно",    phonetic: "[Akno]"    },
      { pt: "Mesa",     target: "Стол",    phonetic: "[Stol]"    },
      { pt: "Cadeira",  target: "Стул",    phonetic: "[Stul]"    },
      { pt: "Cama",     target: "Кровать", phonetic: "[Krovat']" },
      { pt: "Cozinha",  target: "Кухня",   phonetic: "[Kúkhnya]" },
      { pt: "Banheiro", target: "Ванная",  phonetic: "[Vánnaya]" },
      { pt: "Livro",    target: "Книга",   phonetic: "[Kníga]"   },
      { pt: "Telefone", target: "Телефон", phonetic: "[Telefón]" },
    ],
    adjetivos: [
      { pt: "Grande",  target: "Большой",    phonetic: "[Bal'shóy]"   },
      { pt: "Pequeno", target: "Маленький",  phonetic: "[Málen'kiy]"  },
      { pt: "Bonito",  target: "Красивый",   phonetic: "[Krasíviy]"   },
      { pt: "Feio",    target: "Некрасивый", phonetic: "[Nekrasíviy]" },
      { pt: "Rápido",  target: "Быстрый",    phonetic: "[Bístriy]"    },
      { pt: "Lento",   target: "Медленный",  phonetic: "[Myédlenniy]" },
      { pt: "Quente",  target: "Горячий",    phonetic: "[Garyáchiy]"  },
      { pt: "Frio",    target: "Холодный",   phonetic: "[Khalódniy]"  },
      { pt: "Feliz",   target: "Счастливый", phonetic: "[Shastlíviy]" },
      { pt: "Triste",  target: "Грустный",   phonetic: "[Grústniy]"   },
    ],
    frases: [
      { pt: "Quanto custa?",           target: "Сколько стоит?",              phonetic: "[Skól'ko stóit?]"               },
      { pt: "Não entendo",             target: "Я не понимаю",                phonetic: "[Ya ne panimáyu]"               },
      { pt: "Pode repetir?",           target: "Повторите, пожалуйста",       phonetic: "[Pavtaríte, pojáluista]"        },
      { pt: "Onde fica o banheiro?",   target: "Где туалет?",                 phonetic: "[Gdye tualét?]"                 },
      { pt: "Estou com fome",          target: "Я голоден",                   phonetic: "[Ya gólayen]"                   },
      { pt: "Me chamo...",             target: "Меня зовут...",               phonetic: "[Menya zavút...]"               },
      { pt: "Fala português?",         target: "Вы говорите по-португальски?",phonetic: "[Vi gavaríte pa-partugál'ski?]" },
      { pt: "Preciso de ajuda",        target: "Мне нужна помощь",            phonetic: "[Mnye nujná pómash']"           },
      { pt: "Tudo bem?",               target: "Как дела?",                   phonetic: "[Kak delá?]"                    },
      { pt: "Com licença!",            target: "Простите!",                   phonetic: "[Prostíte!]"                    },
      { pt: "Onde fica o hotel?",      target: "Где находится отель?",        phonetic: "[Gdye nakhóditsa otel'?]"       },
      { pt: "Pode me ajudar?",         target: "Вы можете мне помочь?",       phonetic: "[Vi mójete mnye pamóch'?]"      },
      { pt: "Não falo russo bem",      target: "Я плохо говорю по-русски",    phonetic: "[Ya plókho gavaryú pa-rúski]"   },
      { pt: "Qual é o seu nome?",      target: "Как вас зовут?",              phonetic: "[Kak vas zavút?]"               },
      { pt: "Estou perdido(a)",        target: "Я заблудился",                phonetic: "[Ya zabludílsya]"               },
      { pt: "Chame a polícia!",        target: "Вызовите полицию!",           phonetic: "[Vízavite palítsyu!]"           },
      { pt: "Que horas são?",          target: "Который час?",                phonetic: "[Katóry chas?]"                 },
      { pt: "Tem Wi-Fi aqui?",         target: "Здесь есть Wi-Fi?",           phonetic: "[Zdes' yest' Wi-Fi?]"           },
      { pt: "A conta, por favor",      target: "Счёт, пожалуйста",            phonetic: "[Schyot, pojáluista]"           },
      { pt: "Posso pagar com cartão?", target: "Можно оплатить картой?",      phonetic: "[Mójno aplatít' kártay?]"       },
    ],
  },
  fr: {
    cumprimentos: [
      { pt: "Olá",               target: "Salut",           phonetic: null },
      { pt: "Bom dia",           target: "Bonjour",         phonetic: null },
      { pt: "Boa tarde",         target: "Bonsoir",         phonetic: null },
      { pt: "Boa noite",         target: "Bonne nuit",      phonetic: null },
      { pt: "Obrigado/Obrigada", target: "Merci",           phonetic: null },
      { pt: "Por favor",         target: "S'il vous plaît", phonetic: null },
      { pt: "De nada",           target: "De rien",         phonetic: null },
      { pt: "Com licença",       target: "Excusez-moi",     phonetic: null },
      { pt: "Desculpe",          target: "Pardon",          phonetic: null },
      { pt: "Tchau",             target: "Au revoir",       phonetic: null },
    ],
    alimentos: [
      { pt: "Pão",    target: "Pain",    phonetic: null },
      { pt: "Água",   target: "Eau",     phonetic: null },
      { pt: "Carne",  target: "Viande",  phonetic: null },
      { pt: "Fruta",  target: "Fruit",   phonetic: null },
      { pt: "Leite",  target: "Lait",    phonetic: null },
      { pt: "Ovo",    target: "Œuf",     phonetic: null },
      { pt: "Arroz",  target: "Riz",     phonetic: null },
      { pt: "Feijão", target: "Haricot", phonetic: null },
      { pt: "Queijo", target: "Fromage", phonetic: null },
      { pt: "Vinho",  target: "Vin",     phonetic: null },
    ],
    viagem: [
      { pt: "Aeroporto",  target: "Aéroport",  phonetic: null },
      { pt: "Hotel",      target: "Hôtel",     phonetic: null },
      { pt: "Bilhete",    target: "Billet",    phonetic: null },
      { pt: "Passaporte", target: "Passeport", phonetic: null },
      { pt: "Mala",       target: "Valise",    phonetic: null },
      { pt: "Trem",       target: "Train",     phonetic: null },
      { pt: "Ônibus",     target: "Bus",       phonetic: null },
      { pt: "Táxi",       target: "Taxi",      phonetic: null },
      { pt: "Mapa",       target: "Carte",     phonetic: null },
      { pt: "Praia",      target: "Plage",     phonetic: null },
    ],
    verbos: [
      { pt: "Ser/Estar", target: "Être",    phonetic: null },
      { pt: "Ter",       target: "Avoir",   phonetic: null },
      { pt: "Ir",        target: "Aller",   phonetic: null },
      { pt: "Querer",    target: "Vouloir", phonetic: null },
      { pt: "Poder",     target: "Pouvoir", phonetic: null },
      { pt: "Fazer",     target: "Faire",   phonetic: null },
      { pt: "Falar",     target: "Parler",  phonetic: null },
      { pt: "Comer",     target: "Manger",  phonetic: null },
      { pt: "Beber",     target: "Boire",   phonetic: null },
      { pt: "Dormir",    target: "Dormir",  phonetic: null },
    ],
    numeros: [
      { pt: "Um",     target: "Un",     phonetic: null },
      { pt: "Dois",   target: "Deux",   phonetic: null },
      { pt: "Três",   target: "Trois",  phonetic: null },
      { pt: "Quatro", target: "Quatre", phonetic: null },
      { pt: "Cinco",  target: "Cinq",   phonetic: null },
      { pt: "Seis",   target: "Six",    phonetic: null },
      { pt: "Sete",   target: "Sept",   phonetic: null },
      { pt: "Oito",   target: "Huit",   phonetic: null },
      { pt: "Nove",   target: "Neuf",   phonetic: null },
      { pt: "Dez",    target: "Dix",    phonetic: null },
    ],
    cores: [
      { pt: "Vermelho", target: "Rouge",  phonetic: null },
      { pt: "Azul",     target: "Bleu",   phonetic: null },
      { pt: "Amarelo",  target: "Jaune",  phonetic: null },
      { pt: "Verde",    target: "Vert",   phonetic: null },
      { pt: "Branco",   target: "Blanc",  phonetic: null },
      { pt: "Preto",    target: "Noir",   phonetic: null },
      { pt: "Laranja",  target: "Orange", phonetic: null },
      { pt: "Rosa",     target: "Rose",   phonetic: null },
      { pt: "Roxo",     target: "Violet", phonetic: null },
      { pt: "Cinza",    target: "Gris",   phonetic: null },
    ],
    familia: [
      { pt: "Mãe",   target: "Mère",       phonetic: null },
      { pt: "Pai",   target: "Père",       phonetic: null },
      { pt: "Filho", target: "Fils",       phonetic: null },
      { pt: "Filha", target: "Fille",      phonetic: null },
      { pt: "Irmão", target: "Frère",      phonetic: null },
      { pt: "Irmã",  target: "Sœur",       phonetic: null },
      { pt: "Avó",   target: "Grand-mère", phonetic: null },
      { pt: "Avô",   target: "Grand-père", phonetic: null },
      { pt: "Tio",   target: "Oncle",      phonetic: null },
      { pt: "Tia",   target: "Tante",      phonetic: null },
    ],
    corpo: [
      { pt: "Cabeça",  target: "Tête",    phonetic: null },
      { pt: "Olho",    target: "Œil",     phonetic: null },
      { pt: "Nariz",   target: "Nez",     phonetic: null },
      { pt: "Boca",    target: "Bouche",  phonetic: null },
      { pt: "Ouvido",  target: "Oreille", phonetic: null },
      { pt: "Mão",     target: "Main",    phonetic: null },
      { pt: "Pé",      target: "Pied",    phonetic: null },
      { pt: "Coração", target: "Cœur",    phonetic: null },
      { pt: "Costas",  target: "Dos",     phonetic: null },
      { pt: "Perna",   target: "Jambe",   phonetic: null },
    ],
    casa: [
      { pt: "Casa",     target: "Maison",       phonetic: null },
      { pt: "Porta",    target: "Porte",        phonetic: null },
      { pt: "Janela",   target: "Fenêtre",      phonetic: null },
      { pt: "Mesa",     target: "Table",        phonetic: null },
      { pt: "Cadeira",  target: "Chaise",       phonetic: null },
      { pt: "Cama",     target: "Lit",          phonetic: null },
      { pt: "Cozinha",  target: "Cuisine",      phonetic: null },
      { pt: "Banheiro", target: "Salle de bain",phonetic: null },
      { pt: "Livro",    target: "Livre",        phonetic: null },
      { pt: "Telefone", target: "Téléphone",    phonetic: null },
    ],
    adjetivos: [
      { pt: "Grande",  target: "Grand",   phonetic: null },
      { pt: "Pequeno", target: "Petit",   phonetic: null },
      { pt: "Bonito",  target: "Beau",    phonetic: null },
      { pt: "Feio",    target: "Laid",    phonetic: null },
      { pt: "Rápido",  target: "Rapide",  phonetic: null },
      { pt: "Lento",   target: "Lent",    phonetic: null },
      { pt: "Quente",  target: "Chaud",   phonetic: null },
      { pt: "Frio",    target: "Froid",   phonetic: null },
      { pt: "Feliz",   target: "Heureux", phonetic: null },
      { pt: "Triste",  target: "Triste",  phonetic: null },
    ],
    frases: [
      { pt: "Quanto custa?",           target: "Combien ça coûte?",           phonetic: null },
      { pt: "Não entendo",             target: "Je ne comprends pas",         phonetic: null },
      { pt: "Pode repetir?",           target: "Pouvez-vous répéter?",        phonetic: null },
      { pt: "Onde fica o banheiro?",   target: "Où sont les toilettes?",      phonetic: null },
      { pt: "Estou com fome",          target: "J'ai faim",                   phonetic: null },
      { pt: "Me chamo...",             target: "Je m'appelle...",             phonetic: null },
      { pt: "Fala português?",         target: "Parlez-vous portugais?",      phonetic: null },
      { pt: "Preciso de ajuda",        target: "J'ai besoin d'aide",          phonetic: null },
      { pt: "Tudo bem?",               target: "Ça va?",                      phonetic: null },
      { pt: "Com licença!",            target: "Excusez-moi!",                phonetic: null },
      { pt: "Onde fica o hotel?",      target: "Où est l'hôtel?",             phonetic: null },
      { pt: "Pode me ajudar?",         target: "Pouvez-vous m'aider?",        phonetic: null },
      { pt: "Não falo francês bem",    target: "Je ne parle pas bien français",phonetic: null },
      { pt: "Qual é o seu nome?",      target: "Comment vous appelez-vous?",  phonetic: null },
      { pt: "Estou perdido(a)",        target: "Je suis perdu(e)",            phonetic: null },
      { pt: "Chame a polícia!",        target: "Appelez la police!",          phonetic: null },
      { pt: "Que horas são?",          target: "Quelle heure est-il?",        phonetic: null },
      { pt: "Tem Wi-Fi aqui?",         target: "Y a-t-il du Wi-Fi ici?",      phonetic: null },
      { pt: "A conta, por favor",      target: "L'addition, s'il vous plaît", phonetic: null },
      { pt: "Posso pagar com cartão?", target: "Puis-je payer par carte?",    phonetic: null },
    ],
  },
  de: {
    cumprimentos: [
      { pt: "Olá",               target: "Hallo",           phonetic: null },
      { pt: "Bom dia",           target: "Guten Morgen",    phonetic: null },
      { pt: "Boa tarde",         target: "Guten Tag",       phonetic: null },
      { pt: "Boa noite",         target: "Gute Nacht",      phonetic: null },
      { pt: "Obrigado/Obrigada", target: "Danke",           phonetic: null },
      { pt: "Por favor",         target: "Bitte",           phonetic: null },
      { pt: "De nada",           target: "Bitte sehr",      phonetic: null },
      { pt: "Com licença",       target: "Entschuldigung",  phonetic: null },
      { pt: "Desculpe",          target: "Es tut mir leid", phonetic: null },
      { pt: "Tchau",             target: "Auf Wiedersehen", phonetic: null },
    ],
    alimentos: [
      { pt: "Pão",    target: "Brot",    phonetic: null },
      { pt: "Água",   target: "Wasser",  phonetic: null },
      { pt: "Carne",  target: "Fleisch", phonetic: null },
      { pt: "Fruta",  target: "Obst",    phonetic: null },
      { pt: "Leite",  target: "Milch",   phonetic: null },
      { pt: "Ovo",    target: "Ei",      phonetic: null },
      { pt: "Arroz",  target: "Reis",    phonetic: null },
      { pt: "Feijão", target: "Bohne",   phonetic: null },
      { pt: "Queijo", target: "Käse",    phonetic: null },
      { pt: "Vinho",  target: "Wein",    phonetic: null },
    ],
    viagem: [
      { pt: "Aeroporto",  target: "Flughafen", phonetic: null },
      { pt: "Hotel",      target: "Hotel",     phonetic: null },
      { pt: "Bilhete",    target: "Fahrkarte", phonetic: null },
      { pt: "Passaporte", target: "Reisepass", phonetic: null },
      { pt: "Mala",       target: "Koffer",    phonetic: null },
      { pt: "Trem",       target: "Zug",       phonetic: null },
      { pt: "Ônibus",     target: "Bus",       phonetic: null },
      { pt: "Táxi",       target: "Taxi",      phonetic: null },
      { pt: "Mapa",       target: "Karte",     phonetic: null },
      { pt: "Praia",      target: "Strand",    phonetic: null },
    ],
    verbos: [
      { pt: "Ser/Estar", target: "Sein",     phonetic: null },
      { pt: "Ter",       target: "Haben",    phonetic: null },
      { pt: "Ir",        target: "Gehen",    phonetic: null },
      { pt: "Querer",    target: "Wollen",   phonetic: null },
      { pt: "Poder",     target: "Können",   phonetic: null },
      { pt: "Fazer",     target: "Machen",   phonetic: null },
      { pt: "Falar",     target: "Sprechen", phonetic: null },
      { pt: "Comer",     target: "Essen",    phonetic: null },
      { pt: "Beber",     target: "Trinken",  phonetic: null },
      { pt: "Dormir",    target: "Schlafen", phonetic: null },
    ],
    numeros: [
      { pt: "Um",     target: "Eins",   phonetic: null },
      { pt: "Dois",   target: "Zwei",   phonetic: null },
      { pt: "Três",   target: "Drei",   phonetic: null },
      { pt: "Quatro", target: "Vier",   phonetic: null },
      { pt: "Cinco",  target: "Fünf",   phonetic: null },
      { pt: "Seis",   target: "Sechs",  phonetic: null },
      { pt: "Sete",   target: "Sieben", phonetic: null },
      { pt: "Oito",   target: "Acht",   phonetic: null },
      { pt: "Nove",   target: "Neun",   phonetic: null },
      { pt: "Dez",    target: "Zehn",   phonetic: null },
    ],
    cores: [
      { pt: "Vermelho", target: "Rot",     phonetic: null },
      { pt: "Azul",     target: "Blau",    phonetic: null },
      { pt: "Amarelo",  target: "Gelb",    phonetic: null },
      { pt: "Verde",    target: "Grün",    phonetic: null },
      { pt: "Branco",   target: "Weiß",    phonetic: null },
      { pt: "Preto",    target: "Schwarz", phonetic: null },
      { pt: "Laranja",  target: "Orange",  phonetic: null },
      { pt: "Rosa",     target: "Rosa",    phonetic: null },
      { pt: "Roxo",     target: "Lila",    phonetic: null },
      { pt: "Cinza",    target: "Grau",    phonetic: null },
    ],
    familia: [
      { pt: "Mãe",   target: "Mutter",    phonetic: null },
      { pt: "Pai",   target: "Vater",     phonetic: null },
      { pt: "Filho", target: "Sohn",      phonetic: null },
      { pt: "Filha", target: "Tochter",   phonetic: null },
      { pt: "Irmão", target: "Bruder",    phonetic: null },
      { pt: "Irmã",  target: "Schwester", phonetic: null },
      { pt: "Avó",   target: "Oma",       phonetic: null },
      { pt: "Avô",   target: "Opa",       phonetic: null },
      { pt: "Tio",   target: "Onkel",     phonetic: null },
      { pt: "Tia",   target: "Tante",     phonetic: null },
    ],
    corpo: [
      { pt: "Cabeça",  target: "Kopf",   phonetic: null },
      { pt: "Olho",    target: "Auge",   phonetic: null },
      { pt: "Nariz",   target: "Nase",   phonetic: null },
      { pt: "Boca",    target: "Mund",   phonetic: null },
      { pt: "Ouvido",  target: "Ohr",    phonetic: null },
      { pt: "Mão",     target: "Hand",   phonetic: null },
      { pt: "Pé",      target: "Fuß",    phonetic: null },
      { pt: "Coração", target: "Herz",   phonetic: null },
      { pt: "Costas",  target: "Rücken", phonetic: null },
      { pt: "Perna",   target: "Bein",   phonetic: null },
    ],
    casa: [
      { pt: "Casa",     target: "Haus",    phonetic: null },
      { pt: "Porta",    target: "Tür",     phonetic: null },
      { pt: "Janela",   target: "Fenster", phonetic: null },
      { pt: "Mesa",     target: "Tisch",   phonetic: null },
      { pt: "Cadeira",  target: "Stuhl",   phonetic: null },
      { pt: "Cama",     target: "Bett",    phonetic: null },
      { pt: "Cozinha",  target: "Küche",   phonetic: null },
      { pt: "Banheiro", target: "Bad",     phonetic: null },
      { pt: "Livro",    target: "Buch",    phonetic: null },
      { pt: "Telefone", target: "Telefon", phonetic: null },
    ],
    adjetivos: [
      { pt: "Grande",  target: "Groß",     phonetic: null },
      { pt: "Pequeno", target: "Klein",    phonetic: null },
      { pt: "Bonito",  target: "Schön",    phonetic: null },
      { pt: "Feio",    target: "Hässlich", phonetic: null },
      { pt: "Rápido",  target: "Schnell",  phonetic: null },
      { pt: "Lento",   target: "Langsam",  phonetic: null },
      { pt: "Quente",  target: "Heiß",     phonetic: null },
      { pt: "Frio",    target: "Kalt",     phonetic: null },
      { pt: "Feliz",   target: "Glücklich",phonetic: null },
      { pt: "Triste",  target: "Traurig",  phonetic: null },
    ],
    frases: [
      { pt: "Quanto custa?",           target: "Was kostet das?",               phonetic: null },
      { pt: "Não entendo",             target: "Ich verstehe nicht",            phonetic: null },
      { pt: "Pode repetir?",           target: "Können Sie wiederholen?",       phonetic: null },
      { pt: "Onde fica o banheiro?",   target: "Wo ist die Toilette?",          phonetic: null },
      { pt: "Estou com fome",          target: "Ich habe Hunger",               phonetic: null },
      { pt: "Me chamo...",             target: "Ich heiße...",                  phonetic: null },
      { pt: "Fala português?",         target: "Sprechen Sie Portugiesisch?",   phonetic: null },
      { pt: "Preciso de ajuda",        target: "Ich brauche Hilfe",             phonetic: null },
      { pt: "Tudo bem?",               target: "Wie geht es Ihnen?",            phonetic: null },
      { pt: "Com licença!",            target: "Entschuldigung!",               phonetic: null },
      { pt: "Onde fica o hotel?",      target: "Wo ist das Hotel?",             phonetic: null },
      { pt: "Pode me ajudar?",         target: "Können Sie mir helfen?",        phonetic: null },
      { pt: "Não falo alemão bem",     target: "Ich spreche nicht gut Deutsch", phonetic: null },
      { pt: "Qual é o seu nome?",      target: "Wie heißen Sie?",               phonetic: null },
      { pt: "Estou perdido(a)",        target: "Ich habe mich verlaufen",       phonetic: null },
      { pt: "Chame a polícia!",        target: "Rufen Sie die Polizei!",        phonetic: null },
      { pt: "Que horas são?",          target: "Wie spät ist es?",              phonetic: null },
      { pt: "Tem Wi-Fi aqui?",         target: "Gibt es hier WLAN?",            phonetic: null },
      { pt: "A conta, por favor",      target: "Die Rechnung, bitte",           phonetic: null },
      { pt: "Posso pagar com cartão?", target: "Kann ich mit Karte zahlen?",    phonetic: null },
    ],
  },
  en: {
    cumprimentos: [
      { pt: "Hello",           target: "Olá",               phonetic: null, example: "Hello! How are you today?",         tip: "Em português, 'olá' é formal. Entre amigos, diz-se 'oi' ou 'e aí'." },
      { pt: "Good morning",    target: "Bom dia",           phonetic: null, example: "Good morning, would you like coffee?", tip: "'Bom dia' é usado até ao meio-dia. Após isso: 'boa tarde'." },
      { pt: "Good afternoon",  target: "Boa tarde",         phonetic: null, example: "Good afternoon, how can I help?",    tip: "'Tarde' em português vem do latim 'tardus' — mesma raiz de 'tardy' em inglês." },
      { pt: "Good evening",    target: "Boa noite",         phonetic: null, example: "Good evening, welcome to our restaurant.", tip: "'Boa noite' serve tanto para cumprimentar quanto para se despedir à noite." },
      { pt: "Thank you",       target: "Obrigado/Obrigada", phonetic: null, example: "Thank you so much for your help!",   tip: "Masculino: 'obrigado'. Feminino: 'obrigada'. Quem fala é que concorda com o gênero." },
      { pt: "Please",          target: "Por favor",         phonetic: null, example: "One coffee, please.",                tip: "Literalmente 'por favor' — expressão idêntica em espanhol!" },
      { pt: "You're welcome",  target: "De nada",           phonetic: null, example: "—Thank you! —You're welcome!",       tip: "'De nada' literalmente = 'por nada'. Também se diz 'com prazer'." },
      { pt: "Excuse me",       target: "Com licença",       phonetic: null, example: "Excuse me, where is the bathroom?",  tip: "Para pedir desculpas por algo: use 'desculpe' ou 'me desculpe'." },
      { pt: "I'm sorry",       target: "Desculpe",          phonetic: null, example: "I'm so sorry for being late.",       tip: "'Desculpe' = desculpa formal. Entre amigos: 'desculpa' (sem o 'e' final)." },
      { pt: "Goodbye",         target: "Tchau",             phonetic: null, example: "Goodbye, see you tomorrow!",         tip: "'Tchau' vem do italiano 'ciao'! Formal: 'até logo' ou 'até breve'." },
    ],
    alimentos: [
      { pt: "Bread",  target: "Pão",    phonetic: null, example: "I'd like some bread, please.",     tip: "'Pão' é plural de pão — 'pães'. O pão de queijo é símbolo de Minas Gerais." },
      { pt: "Water",  target: "Água",   phonetic: null, example: "Can I have a glass of water?",     tip: "O acento 'á' indica sílaba tônica. Sem acento mudaria o significado." },
      { pt: "Meat",   target: "Carne",  phonetic: null, example: "How would you like your meat?",    tip: "Brasil é um dos maiores produtores e consumidores de carne bovina do mundo." },
      { pt: "Fruit",  target: "Fruta",  phonetic: null, example: "I eat fruit every morning.",       tip: "Brasil tem frutas únicas: açaí, cupuaçu, jabuticaba, pitanga..." },
      { pt: "Milk",   target: "Leite",  phonetic: null, example: "Do you want milk in your coffee?", tip: "'Café com leite' é o café da manhã clássico brasileiro." },
      { pt: "Egg",    target: "Ovo",    phonetic: null, example: "I'd like two fried eggs.",         tip: "Plural: 'ovos'. 'Ovos mexidos' = scrambled eggs. 'Ovo frito' = fried egg." },
      { pt: "Rice",   target: "Arroz",  phonetic: null, example: "Rice and beans every day!",        tip: "'Arroz e feijão' é o prato nacional brasileiro — base de quase toda refeição." },
      { pt: "Beans",  target: "Feijão", phonetic: null, example: "Black beans are delicious.",       tip: "'Feijão' vem de 'phaseolus' (latim). 'Feijoada' é o prato mais famoso do Brasil." },
      { pt: "Cheese", target: "Queijo", phonetic: null, example: "Brazil has amazing cheese!",       tip: "Minas Gerais é famosa pelo 'queijo minas' — patrimônio cultural imaterial." },
      { pt: "Wine",   target: "Vinho",  phonetic: null, example: "Would you like red or white wine?", tip: "Vale dos Vinhedos (RS) é a melhor região vinícola do Brasil." },
    ],
    viagem: [
      { pt: "Airport",   target: "Aeroporto",  phonetic: null, example: "What time does the flight leave the airport?", tip: "Guarulhos (SP) e Galeão (RJ) são os maiores aeroportos internacionais do Brasil." },
      { pt: "Hotel",     target: "Hotel",      phonetic: null, example: "I have a reservation at this hotel.",          tip: "Mesma palavra! Em português o 'h' é mudo — pronuncia-se 'o-TÉL'." },
      { pt: "Ticket",    target: "Bilhete",    phonetic: null, example: "I'd like two tickets, please.",                tip: "'Bilhete' para ônibus/trem. 'Passagem' é mais comum para avião." },
      { pt: "Passport",  target: "Passaporte", phonetic: null, example: "Don't forget your passport.",                 tip: "O passaporte brasileiro tem cor verde — identificável no mundo todo." },
      { pt: "Suitcase",  target: "Mala",       phonetic: null, example: "My suitcase is too heavy.",                   tip: "'Mala' = mala de viagem. 'Bolsa' = bolsa de mão. 'Mochila' = mochila." },
      { pt: "Train",     target: "Trem",       phonetic: null, example: "The train leaves at 9am.",                    tip: "Brasil tem metrô em SP, RJ, BH e outras cidades. 'Metrô' = metro/subway." },
      { pt: "Bus",       target: "Ônibus",     phonetic: null, example: "Which bus goes to the center?",               tip: "Brasil tem a maior rede de ônibus interestaduais do mundo — conecta todo o país." },
      { pt: "Taxi",      target: "Táxi",       phonetic: null, example: "Can you call me a taxi?",                     tip: "99 e Uber são os apps mais populares no Brasil. 'Táxi' tem acento agudo." },
      { pt: "Map",       target: "Mapa",       phonetic: null, example: "Do you have a map of the city?",              tip: "Mesma palavra! Pronunciada 'MApa' em português (tônica na primeira sílaba)." },
      { pt: "Beach",     target: "Praia",      phonetic: null, example: "Let's go to the beach!",                      tip: "Brasil tem 7.491 km de litoral — Copacabana, Ipanema e Barra são as mais famosas." },
    ],
    verbos: [
      { pt: "To be",    target: "Ser/Estar", phonetic: null, example: "I want to be a doctor.",    tip: "Português diferencia: 'ser' (permanente) e 'estar' (temporário) — como espanhol." },
      { pt: "To have",  target: "Ter",       phonetic: null, example: "I have two brothers.",      tip: "'Tenho' (1ª pessoa). 'Tenho fome' = I'm hungry (literalmente 'tenho fome')." },
      { pt: "To go",    target: "Ir",        phonetic: null, example: "I'm going to the market.",  tip: "'Vou' (eu vou). 'Vou + infinitivo' = futuro próximo: 'vou comer'." },
      { pt: "To want",  target: "Querer",    phonetic: null, example: "I want to learn Portuguese.", tip: "'Quero' (eu quero). 'Querer bem' = to care for/love someone." },
      { pt: "Can/May",  target: "Poder",     phonetic: null, example: "Can you speak more slowly?", tip: "'Posso' (eu posso). 'Pode falar mais devagar?' — frase essencial!" },
      { pt: "To do",    target: "Fazer",     phonetic: null, example: "What are you doing today?", tip: "'Faço' (eu faço). 'Fazer' é usado para clima: 'está fazendo calor'." },
      { pt: "To speak", target: "Falar",     phonetic: null, example: "Do you speak English?",     tip: "'Falo' (eu falo). 'Você fala inglês?' — pergunta que você vai ouvir muito!" },
      { pt: "To eat",   target: "Comer",     phonetic: null, example: "Let's eat, I'm starving!",  tip: "'Como' (eu como). 'Bora comer!' = informal brasileira para 'vamos comer'." },
      { pt: "To drink", target: "Beber",     phonetic: null, example: "What would you like to drink?", tip: "'Bebo' (eu bebo). 'Tomar' também é usado: 'tomar café/água'." },
      { pt: "To sleep", target: "Dormir",    phonetic: null, example: "I need to sleep, I'm tired.", tip: "'Durmo' (eu durmo). 'Estou com sono' = I'm sleepy (tenho sono)." },
    ],
    numeros: [
      { pt: "One",   target: "Um",     phonetic: null, example: "One coffee, please.",         tip: "Masculino: 'um'. Feminino: 'uma'. 'Uma xícara de café' = a cup of coffee." },
      { pt: "Two",   target: "Dois",   phonetic: null, example: "Table for two, please.",      tip: "Feminino: 'duas'. 'Dois homens / duas mulheres' — gênero importa!" },
      { pt: "Three", target: "Três",   phonetic: null, example: "I'll be there in three minutes.", tip: "O acento circunflexo (ê) indica vogal fechada — soa diferente de 'tres' espanhol." },
      { pt: "Four",  target: "Quatro", phonetic: null, example: "Four seasons in Brazil.",     tip: "'Quatro estações' — Brasil tem verão, outono, inverno e primavera bem definidos." },
      { pt: "Five",  target: "Cinco",  phonetic: null, example: "Five minutes, please.",       tip: "Pronuncia-se 'SINco' — o 'c' antes de 'i' soa como 's' em português." },
      { pt: "Six",   target: "Seis",   phonetic: null, example: "The store closes at six.",    tip: "Pronuncia-se 'SEIS' (rima com 'reis'). Plural de 'rei' = 'reis' — coincidência!" },
      { pt: "Seven", target: "Sete",   phonetic: null, example: "Seven days in a week.",       tip: "Pronuncia-se 'SÉte'. 'Sete e meia' = 7:30 (seven thirty)." },
      { pt: "Eight", target: "Oito",   phonetic: null, example: "I work eight hours a day.",   tip: "Pronuncia-se 'ÔIto'. O ditongo 'oi' não existe em inglês — treinar é importante." },
      { pt: "Nine",  target: "Nove",   phonetic: null, example: "Nine lives, just like a cat!", tip: "Pronuncia-se 'NÓve'. 'Noventa' = ninety. 'Novecentos' = nine hundred." },
      { pt: "Ten",   target: "Dez",    phonetic: null, example: "Ten real, please.",            tip: "'Dez reais' — plural de 'real' (moeda brasileira) é 'reais'." },
    ],
    cores: [
      { pt: "Red",    target: "Vermelho", phonetic: null, example: "The Brazilian flag has green, yellow and red.", tip: "A bandeira do Brasil tem verde, amarelo, azul e branco — não vermelho!" },
      { pt: "Blue",   target: "Azul",     phonetic: null, example: "The sky is blue today.",    tip: "Mesma escrita que em espanhol! 'Azul' vem do árabe 'lazaward'." },
      { pt: "Yellow", target: "Amarelo",  phonetic: null, example: "Yellow is the color of sunshine.", tip: "O amarelo na bandeira brasileira representa o ouro — riqueza mineral do país." },
      { pt: "Green",  target: "Verde",    phonetic: null, example: "Brazil is famous for its green forests.", tip: "O verde da bandeira representa as matas do Brasil. Amazônia = pulmão do mundo." },
      { pt: "White",  target: "Branco",   phonetic: null, example: "White sand beaches are beautiful.", tip: "'Branco' (m) / 'branca' (f). 'Página em branco' = blank page." },
      { pt: "Black",  target: "Preto",    phonetic: null, example: "Black beans and rice is a classic.", tip: "'Feijão preto' = black beans — base da feijoada, prato nacional." },
      { pt: "Orange", target: "Laranja",  phonetic: null, example: "Fresh orange juice for breakfast.",   tip: "'Laranja' = laranja a cor E a fruta. 'Suco de laranja' = orange juice." },
      { pt: "Pink",   target: "Rosa",     phonetic: null, example: "Pink is a popular color.",            tip: "Mesma palavra para a cor e a flor rosa. 'Cor-de-rosa' = pink (literalmente)." },
      { pt: "Purple", target: "Roxo",     phonetic: null, example: "Purple is the color of royalty.",     tip: "'Roxo de raiva' = purple with rage — expressão idiomática brasileira." },
      { pt: "Gray",   target: "Cinza",    phonetic: null, example: "Gray clouds in the sky.",             tip: "'Cinza' também é a palavra para 'cinzas' (ashes) — mesma palavra." },
    ],
    familia: [
      { pt: "Mother",      target: "Mãe",   phonetic: null, example: "My mother is an amazing cook.",    tip: "O til (~) nasaliza a vogal. 'Mãe' soa 'mãĩ' — difícil para anglófonos!" },
      { pt: "Father",      target: "Pai",   phonetic: null, example: "My father works in São Paulo.",    tip: "Informal: 'pai' já é informal! Muito mais curto que 'father'. Carinhoso: 'paizinho'." },
      { pt: "Son",         target: "Filho", phonetic: null, example: "My son is five years old.",        tip: "'Lho' tem som 'lyu' — o 'lh' é dígrafo específico do português." },
      { pt: "Daughter",    target: "Filha", phonetic: null, example: "My daughter loves music.",         tip: "'Minha filha' — 'minha' = my (feminine). 'Meu filho' = my son." },
      { pt: "Brother",     target: "Irmão", phonetic: null, example: "I have two brothers.",             tip: "O til em 'irmão' é o som nasal. Plural: 'irmãos'. Feminino: 'irmã'." },
      { pt: "Sister",      target: "Irmã",  phonetic: null, example: "My sister lives in Rio.",          tip: "Plural: 'irmãs'. A família brasileira é muito unida — família extensa é normal." },
      { pt: "Grandmother", target: "Avó",   phonetic: null, example: "My grandmother makes the best food.", tip: "Acento agudo (ó) = vogal aberta. 'Vovó' é o diminutivo carinhoso." },
      { pt: "Grandfather", target: "Avô",   phonetic: null, example: "My grandfather tells great stories.", tip: "Acento circunflexo (ô) = vogal fechada. 'Vovô' é o carinhoso. Notar a diferença avó/avô!" },
      { pt: "Uncle",       target: "Tio",   phonetic: null, example: "My uncle lives in Minas Gerais.",  tip: "Pronuncia-se 'CHIo' — o 't' antes de 'i' vira 'tch' no português brasileiro!" },
      { pt: "Aunt",        target: "Tia",   phonetic: null, example: "My aunt makes amazing coxinha.",   tip: "'Tia' também é usado para chamar professoras na escola. Cultura brasileira." },
    ],
    corpo: [
      { pt: "Head",    target: "Cabeça",  phonetic: null, example: "I have a headache.",              tip: "'Dor de cabeça' = headache. 'Cabeça' — o 'ç' soa 'ss'." },
      { pt: "Eye",     target: "Olho",    phonetic: null, example: "She has beautiful eyes.",          tip: "Plural: 'olhos'. 'Olho gordo' = evil eye — crença cultural brasileira." },
      { pt: "Nose",    target: "Nariz",   phonetic: null, example: "My nose is cold.",                 tip: "Pronuncia-se 'naRIS'. O 'z' final soa 's' em posição final no Brasil." },
      { pt: "Mouth",   target: "Boca",    phonetic: null, example: "Open your mouth, please.",         tip: "Mesma raiz de 'vocal'. 'Boca de siri' = keep it secret (boca fechada)." },
      { pt: "Ear",     target: "Ouvido",  phonetic: null, example: "I have an ear infection.",         tip: "'Orelha' = outer ear. 'Ouvido' = inner ear/hearing. Distinção importante." },
      { pt: "Hand",    target: "Mão",     phonetic: null, example: "Give me your hand.",               tip: "O til nasaliza: 'mãõ'. Plural: 'mãos'. 'Dar uma mão' = to help someone." },
      { pt: "Foot",    target: "Pé",      phonetic: null, example: "My foot hurts.",                   tip: "Acento agudo. 'Pé' = foot. 'A pé' = on foot (walking). Plural: 'pés'." },
      { pt: "Heart",   target: "Coração", phonetic: null, example: "My heart is beating fast.",        tip: "O 'ç' soa 'ss'. 'Coração' tem til nasal no final — som difícil para anglófonos." },
      { pt: "Back",    target: "Costas",  phonetic: null, example: "My back hurts from sitting.",      tip: "Sempre no plural: 'as costas'. 'Virar as costas' = to turn one's back on someone." },
      { pt: "Leg",     target: "Perna",   phonetic: null, example: "I broke my leg playing soccer.",   tip: "Brasil tem o futebol no DNA — 'perna' é essencial no vocabulário esportivo!" },
    ],
    casa: [
      { pt: "House",    target: "Casa",     phonetic: null, example: "Welcome to my house!",           tip: "'Minha casa é a sua casa' = my home is your home — expressão de hospitalidade." },
      { pt: "Door",     target: "Porta",    phonetic: null, example: "Please close the door.",         tip: "'Porta' também = gate (portão grande). 'Bater à porta' = to knock on the door." },
      { pt: "Window",   target: "Janela",   phonetic: null, example: "Open the window, it's hot!",     tip: "'Janela' = window. 'Vitrine' = shop window. 'Janelinha' = little window." },
      { pt: "Table",    target: "Mesa",     phonetic: null, example: "Let's sit at the table.",        tip: "Mesma escrita que em espanhol! 'Pôr a mesa' = to set the table." },
      { pt: "Chair",    target: "Cadeira",  phonetic: null, example: "Please take a seat.",            tip: "'Cadeira' = chair. 'Poltrona' = armchair. 'Cadeirinha' = baby/car seat." },
      { pt: "Bed",      target: "Cama",     phonetic: null, example: "I'm going to bed now.",          tip: "'Ir para a cama' = to go to bed. 'Cama' mesma palavra que em espanhol." },
      { pt: "Kitchen",  target: "Cozinha",  phonetic: null, example: "Brazilian cuisine is amazing!",  tip: "'Cozinha' = kitchen e culinária. 'Cozinheiro/a' = chef/cook." },
      { pt: "Bathroom", target: "Banheiro", phonetic: null, example: "Where is the bathroom?",         tip: "'Banheiro' no Brasil. Em Portugal dizem 'casa de banho'. 'WC' também é usado." },
      { pt: "Book",     target: "Livro",    phonetic: null, example: "I love reading books.",          tip: "'Livraria' = bookstore (not library!). 'Biblioteca' = library. Cuidado!" },
      { pt: "Phone",    target: "Telefone", phonetic: null, example: "What's your phone number?",      tip: "'Celular' = mobile phone. 'Telefone' é mais o fixo. 'Carregador' = charger." },
    ],
    adjetivos: [
      { pt: "Big",       target: "Grande",  phonetic: null, example: "Brazil is a very big country.",  tip: "Mesma palavra em espanhol e italiano! Do latim 'grandis'." },
      { pt: "Small",     target: "Pequeno", phonetic: null, example: "A small coffee, please.",        tip: "Feminino: 'pequena'. 'Um café pequeno' = espresso shot no Brasil." },
      { pt: "Beautiful", target: "Bonito",  phonetic: null, example: "What a beautiful city!",         tip: "Mesma palavra em espanhol! 'Lindo/a' é mais intenso e também muito usado." },
      { pt: "Ugly",      target: "Feio",    phonetic: null, example: "The weather is ugly today.",     tip: "'Tempo feio' = bad weather. 'Feio' tem uso mais amplo que 'ugly' em inglês." },
      { pt: "Fast",      target: "Rápido",  phonetic: null, example: "This is a fast car!",            tip: "Mesma palavra em espanhol! 'Rápido!' também é exclamação = hurry up!" },
      { pt: "Slow",      target: "Lento",   phonetic: null, example: "Please speak slowly.",           tip: "Mesma palavra em português, espanhol e italiano. 'Devagar' = slowly (advérbio)." },
      { pt: "Hot",       target: "Quente",  phonetic: null, example: "It's very hot in Rio!",          tip: "Clima: 'está quente'. Sensação: 'estou com calor'. Não confundir os dois!" },
      { pt: "Cold",      target: "Frio",    phonetic: null, example: "It's cold in the south of Brazil.", tip: "Clima: 'está frio'. Sensação: 'estou com frio'. O sul do Brasil tem inverno real!" },
      { pt: "Happy",     target: "Feliz",   phonetic: null, example: "Happy birthday!",                tip: "'Feliz aniversário!' = Happy birthday! 'Feliz' mesma palavra em espanhol." },
      { pt: "Sad",       target: "Triste",  phonetic: null, example: "I'm sad today.",                 tip: "Mesma palavra nos três idiomas: português, espanhol e italiano. Do latim 'tristis'." },
    ],
    frases: [
      { pt: "How much is it?",            target: "Quanto custa?",           phonetic: null, example: "Excuse me, how much is this?",            tip: "'Custa' vem de 'custar'. 'Quanto custa isso?' é a forma completa." },
      { pt: "I don't understand",         target: "Não entendo",             phonetic: null, example: "Sorry, I don't understand Portuguese.",    tip: "'Não entendo português' — dizer isso em PT mostra esforço e abre portas!" },
      { pt: "Can you repeat that?",       target: "Pode repetir?",           phonetic: null, example: "Sorry, can you repeat that more slowly?",  tip: "'Mais devagar' = more slowly. Essencial ao aprender português!" },
      { pt: "Where is the bathroom?",     target: "Onde fica o banheiro?",   phonetic: null, example: "Excuse me, where is the bathroom?",        tip: "'Onde fica' = where is (located). Mais formal que simplesmente 'onde é'." },
      { pt: "I'm hungry",                 target: "Estou com fome",          phonetic: null, example: "I'm so hungry, let's eat!",                tip: "Literalmente 'estou com fome' — em português usa-se 'estar com fome'." },
      { pt: "My name is...",              target: "Me chamo...",             phonetic: null, example: "Hi, my name is John.",                     tip: "Literalmente 'me chamo' = I call myself. Construção reflexiva." },
      { pt: "Do you speak Portuguese?",   target: "Fala português?",         phonetic: null, example: "Excuse me, do you speak Portuguese?",      tip: "Omitir o pronome ('você') é muito comum no Brasil. 'Fala' sozinho = you speak." },
      { pt: "I need help",                target: "Preciso de ajuda",        phonetic: null, example: "Help! I need help, I'm lost.",              tip: "'Preciso de' = I need (something). Estrutura muito útil em PT." },
      { pt: "How are you?",               target: "Tudo bem?",               phonetic: null, example: "Hey! How are you? All good?",              tip: "Resposta: 'Tudo bem, obrigado!' ou 'Tudo ótimo!' — muito informais e calorosos." },
      { pt: "Excuse me!",                 target: "Com licença!",            phonetic: null, example: "Excuse me, can I get past?",               tip: "'Com licença' para passar. Para chamar atenção: 'com licença' ou 'desculpe'." },
      { pt: "Where is the hotel?",        target: "Onde fica o hotel?",      phonetic: null, example: "Excuse me, where is the hotel?",           tip: "'Fica' (from 'ficar') = is located. Very Brazilian way to ask directions." },
      { pt: "Can you help me?",           target: "Pode me ajudar?",         phonetic: null, example: "Excuse me, can you help me?",              tip: "'Pode' = can/may (você). 'Me ajudar' = help me. Ordem inversa ao inglês." },
      { pt: "I don't speak Portuguese well", target: "Não falo português bem", phonetic: null, example: "Sorry, I don't speak Portuguese well.",  tip: "Brasileiros adoram quando estrangeiros tentam falar português — diga isso!" },
      { pt: "What is your name?",         target: "Qual é o seu nome?",      phonetic: null, example: "Nice to meet you! What is your name?",     tip: "Informal: 'Como você se chama?' ou 'Qual é o seu nome?' — ambos corretos." },
      { pt: "I'm lost",                   target: "Estou perdido(a)",        phonetic: null, example: "I'm lost, can you help me?",               tip: "Masculino: 'perdido'. Feminino: 'perdida'. Gênero concorda com quem fala." },
      { pt: "Call the police!",           target: "Chame a polícia!",        phonetic: null, example: "Call the police! I've been robbed!",       tip: "'Socorro!' = Help! Grite isso em emergência no Brasil." },
      { pt: "What time is it?",           target: "Que horas são?",          phonetic: null, example: "Excuse me, what time is it?",              tip: "Resposta: 'São três horas' (it's three o'clock). 'É uma hora' = it's one o'clock." },
      { pt: "Is there Wi-Fi here?",       target: "Tem Wi-Fi aqui?",         phonetic: null, example: "Is there Wi-Fi here? What's the password?", tip: "'Senha' = password. 'Tem Wi-Fi?' — 'tem' = there is (informal brasileiro)." },
      { pt: "The bill, please",           target: "A conta, por favor",      phonetic: null, example: "Waiter, the bill please!",                 tip: "'Garçom' = waiter (m). 'Garçonete' = waitress. 'A conta' = the check/bill." },
      { pt: "Can I pay by card?",         target: "Posso pagar com cartão?", phonetic: null, example: "Can I pay by card or cash only?",          tip: "'Dinheiro' = cash. 'Cartão de crédito/débito' = credit/debit card." },
    ],
  },
};
